# https://github.com/t3n/helm-charts/blob/master/promtail/values.yaml

initContainer:
  - name: init
    image: docker.io/busybox:1.33
    imagePullPolicy: IfNotPresent
    command:
      - sh
      - -c
      - sysctl -w fs.inotify.max_user_instances=4096
    securityContext:
      privileged: true   

config:
  logLevel: debug
  clients:
    - url: http://loki-gateway/loki/api/v1/push
      batchwait: 1s
      batchsize: 1048576
      basic_auth:
        username: ${LOKI_USERNAME}
        password: ${LOKI_PASSWORD}

  snippets:
    pipelineStages:
      - cri: {}
      - match:
          selector: '{app=~".+"}'
          stages:
            - cri: {}
            - json:
                expressions:
                  level: level
                  status: status
                  hostname: hostname
                  userAgent: user_agent
            - labels:
                level:
                status:
                hostname:
            - drop:
                source:     "userAgent"
                expression: ".*kube-probe.*"                  
    
    # Open issue here: https://github.com/grafana/helm-charts/issues/197
    extraScrapeConfigs: |
      - job_name: journal
        journal:
          path: /var/log/journal
          max_age: 12h
          labels:
            job: systemd-journal
        relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__hostname']
            target_label: 'hostname' 

  backoff_config:
    min_period: 500ms
    max_period: 5m
    max_retries: 10            
  


extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal

extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true        